language: node_js
node_js:
  - "15"
before_script: npm run build
deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY
  bucket: oliverzheng.com
  endpoint: oliverzheng.com.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  local_dir: build
  skip_cleanup: true
  acl: public_read
  on:
    repo: oliverzheng/oliverzheng.com
